config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :users, only: [:show], param: :username
  resources :attachments
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  match '/sessions/getonetoken', to: 'sessions#token', via: 'get'
  match '/issues/:id/vote', to: 'issues#vote', via: 'post'
  match '/issues/:id/comments', to: 'issues#comment', via: 'post'
  match '/issues/:id/comments', to: 'issues#index_comment', via: 'get'
  match '/issues/:issue_id/comments/:comment_id', to: 'issues#comment_destroy', via: 'delete'
  match '/issues/:issue_id/comments/:comment_id', to: 'issues#getonecomment', via: 'get'
  match '/issues/:issue_id/comments/:comment_id', to: 'issues#update_comment', via: 'patch'
  match '/issues/:id/unvote', to: 'issues#unvote', via: 'post'
  match '/issues/:id/follow', to: 'issues#follow', via: 'post'
  match '/issues/:id/unfollow', to: 'issues#unfollow', via: 'post'
  match '/issues/new', to: 'issues#create', via: 'post'
  match '/issues/:issue_id/comments/file/:comment_id', to: 'issues#upload_file', via: 'patch'
  match '/issues/:issue_id/comments/:comment_id', to: 'issues#getonecomment', via: 'get'
  match '/users', to: 'users#index', via: 'get'
  match '/sessions/login', to: 'sessions#login', via: 'get'
  match '/sessions/red', to: 'sessions#red', via: 'get'

  resources :issues
  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :vote, dependent: :delete_all
  has_many :watch, dependent: :delete_all
  has_many :comment, dependent: :delete_all
  has_one :assign,  dependent: :destroy
  scope :tipus, -> (tipus) { where tipus: tipus }
  scope :priority, -> (priority) { where priority: priority }
  scope :status, -> (status) { where status: status }
  scope :assign, -> (user) { where stringassign: user}
  scope :follow, -> (user) { where watch: User.find_by_username(user).watch}

  belongs_to :user
  before_create :get_created

  validates :title, presence: true
  validates :description, presence: true


  def get_created
    self.created = Date.today
  end

end

app/controllers/issues_controller.rb
require 'date'
require 'carrierwave/orm/activerecord'

class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :vote, :unvote, :follow, :unfollow, :index_comment, :comment]
  before_action :set_comment, only: [:update_comment, :comment_destroy, :getonecomment]
  
  #POST /issues/1/vote
  def vote
    if !current_user.blank?
      if  @issue.vote.length()==0
      @issue.votes=@issue.votes+1
      user=User.find_by_username(current_user.username)
      vote= Vote.new()
      vote.issue=@issue
      vote.user=user
      user.vote.push(vote)
      @issue.vote.push(vote)
      @issue.save!
      vote.save!
      user.save!
      elsif (@issue.vote & User.find_by_username(current_user.username).vote).length()==0
        @issue.votes=@issue.votes+1
        user=User.find_by_username(current_user.username)
        vote= Vote.new()
        vote.issue=@issue
        vote.user=user
        user.vote.push(vote)
        @issue.vote.push(vote)
        @issue.save!
        vote.save!
        user.save!
      end
      if (request.format.symbol == :html)
        redirect_to :controller => 'issues', :action => 'show'
      end
      if (request.format.symbol == :json)
        
        render json: {"Message":"Vote successfully registered", status: '200'}
      end
    end
  end

  #POST /issues/1/follow
  def follow
    if  !current_user.blank?
      if  @issue.watch.length()==0
        user=User.find_by_username(current_user.username)
        watch= Watch.new()
        watch.issue=@issue
        watch.user=user
        user.watch.push(watch)
        @issue.watch.push(watch)
        @issue.save!
        watch.save!
        user.save!
      elsif (@issue.watch & User.find_by_username(current_user.username).watch).length()==0
        user=User.find_by_username(current_user.username)
        watch= Watch.new()
        watch.issue=@issue
        watch.user=user
        user.watch.push(watch)
        @issue.watch.push(watch)
        @issue.save!
        watch.save!
        user.save!
      end
      if (request.format.symbol == :html)
        redirect_to :controller => 'issues', :action => 'show'
      end
      if (request.format.symbol == :json)
        render json: {"Message":"Follow successfully registered", status: '200'}
      end
    end
  end

  #POST /issues/1/unfollow
  def unfollow
    if  !current_user.blank?
      if (@issue.watch & User.find_by_username(current_user.username).watch).length()>0
        user=User.find_by_username(current_user.username)
        vote=@issue.watch & user.watch
        user=User.find_by_username(current_user.username)
        for item in vote
          item.destroy
          user.watch.delete(item)
          @issue.watch.delete(item)
        end
        @issue.save!
        user.save!
      end
      if (request.format.symbol == :html)
        redirect_to :controller => 'issues', :action => 'show'
      end
      if (request.format.symbol == :json)
        render json: {"Message":"Unfollow successfully registered", status: '200'}
      end
    end
  end


  #POST /issues/1/unvote
  def unvote
    if  !current_user.blank?
      if (@issue.vote & User.find_by_username(current_user.username).vote).length()>0
        @issue.votes=@issue.votes-1
        user=User.find_by_username(current_user.username)
        vote=@issue.vote & user.vote
        for item in vote
          user.vote.delete(item)
          @issue.vote.delete(item)
          item.destroy!
        end
        @issue.save!
        user.save!
      end
      if (request.format.symbol == :html)
        redirect_to :controller => 'issues', :action => 'show'
      end
      if (request.format.symbol == :json)
        render json: {"Message":"Unvote successfully registered", status: '200'}
      end
    end
  end



  # GET /issues
  # GET /issues.json
  def index
    if (!current_user.blank?)
      sesi=cookies[:ses]
      cookies.delete :ses
    if (!sesi.blank? && !SessionUser.find_by_sessionId(sesi).blank?)
      puts "----------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------"
      se=SessionUser.find_by_sessionId(sesi)
      if (!se.blank?)
      callback=se.callback
      se.destroy!
      if (!callback.blank?)
      redirect_to callback+"?token="+current_user.api_token.token+"&username="+current_user.username
        end
      end
    end
    end
    @issues = Issue.where(nil)
    paramsFiltered=filtering_params(params)
    issuelist=Array.new
    if paramsFiltered.keys.include? "ordered_by_follow"
      user=User.find_by_username(current_user.username)
      watch=user.watch
      issuelist=Array.new
      for v in watch
        issuelist.push(v.issue)
      end
    end


    paramsFiltered.each do |key, value|
      @issues = @issues.public_send(key, value) if value.present?
    end
    if paramsFiltered.keys.include? "ordered_by_tipus"
      @issues = @issues.order("tipus asc")
    end
    if paramsFiltered.keys.include? "ordered_by_priority"
      @issues = @issues.order("priority asc")
    end
    if paramsFiltered.keys.include? "ordered_by_status"
      @issues = @issues.order("status asc")
    end
    if paramsFiltered.keys.include? "ordered_by_votes"
      @issues = @issues.order("votes desc")
    end
    if paramsFiltered.keys.include? "ordered_by_assignee"
      @issues = @issues.order("stringassign asc")
      end
    if paramsFiltered.keys.include? "ordered_by_created"
      @issues = @issues.order("created desc")
    end
    if paramsFiltered.keys.include? "ordered_by_updated"
      @issues = @issues.order("updated desc")
    end
    if paramsFiltered.keys.include? "ordered_by_title"
      @issues = @issues.order("title asc")
    end
    if paramsFiltered.keys.include? "ordered_by_follow"
      @issues=@issues & issuelist
    end
    
    if (request.format.symbol == :json) 
        issuelist = Array.new
        @issues.each do |issue|
          if !issue.nil?
            issuelist.push(get_issue_hal(issue))
            end
        end
        render json: issuelist, status: :ok
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
      if (request.format.symbol == :json)
          render json: get_issue_hal(@issue), status: :ok
      end
  end

  # GET /issues/new
  def new
    if !current_user.username.blank?
        @issue = Issue.new()
        @issue.votes=0
        @issue.user =User.find_by_username(current_user.username)
    else 
        redirect_to getHostFromIssues+"/sessions/new"
    end
  end

  # GET /issues/1/edit
  def edit
  end
  
  # GET /issues/{issue_id}/comment
  def index_comment
      if (request.format.symbol == :json)
          commentlist = Array.new
          @issue.comment.each do |comment|
              commentlist.push(get_comment_hal(comment))
          end
          render json: commentlist, status: :ok
      end
  end
  
  # GET /issues/{issue_id}/comment/{comment_id}
  def getonecomment
      if !@issue.blank? && !@comment.blank?
          render json: get_comment_hal(@comment), status: :ok
      end
  end
  
  # GET /issues/{issue_id}/comment/{comment_id}
  def edit_comment
      @issue = Issue.find_by_id(params[:issue_id])
      @comment = Comment.find_by_id(params[:comment_id])
  end

  # POST /issues/new
  # POST /issues/new
  def create
    if (request.format.symbol == :html and check_enum_values(params[:issue][:status],params[:issue][:tipus],params[:issue][:priority]))
        ass=nil
        if !current_user.username.blank?
            @issue = Issue.new(issue_params.except(:name))
                us=User.find_by_username(params[:issue][:name])
                @issue.stringassign=us.username
            end
        elsif (request.format.symbol == :json and check_enum_values(params[:status],params[:tipus],params[:priority]))
          @issue = Issue.new()
          @issue.tipus=params[:tipus]
          @issue.priority=params[:priority]
          @issue.status=params[:status]
          @issue.title=params[:title]
          @issue.description=params[:description]
          if !params[:assigne].blank?

              us = User.find_by_username(params[:assigne]);
            if us.blank?
              us = User.find_by_username(current_user.username);
            end
          else
            us = User.find_by_username(current_user.username);
          end
          @issue.stringassign=us.username
    end

        @issue.votes=0
        @issue.user =User.find_by_username(current_user.username)
        d=Date.today
        @issue.updated=d
        @issue.created=d
        respond_to do |format|
        if @issue.save
            format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
            format.json { render json: get_issue_hal(@issue), status: :ok }
        else
            format.html { render :new }
            format.json { render json: @issue.errors, status: :unprocessable_entity }
        end
        end
  end
  
  # POST /issues/{id}/comment
  def comment
    if !current_user.username.blank?
    @comment = Comment.new()
    if request.format.symbol == :html
        t = params[:comment][:text]
    else 
        t = params[:text]
    end
    if ((t.nil? or t.empty?) and request.format.symbol == :json)
        render_json_error('Text field is not defined', :bad_request)
    end
    @comment.text = t
    @comment.user = User.find_by_username(current_user.username)
    @comment.issue = @issue
    if request.format.symbol == :html
    if (params[:comment].include? "attachment_identifier")
      pos=Post.new()
      pos.attachment_identifier=params[:comment][:attachment_identifier]
      pos.comment=@comment
      pos.save!
      @comment.post.push(pos)
    end
    elsif request.format.symbol == :json
      pos=Post.new()
      pos.attachment_identifier=nil
      pos.comment=@comment

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
  <%= form_with(model: @issue, local: true) do |form| %>

  <% t = 0
     d = 0
     if issue.errors.any? 
        if issue.errors.include? 'title'
            t = 1
        end
        if issue.errors.include? 'description'
            d = 1
        end
     issue.errors.clear
     end%>

  <%= stylesheet_link_tag "mime1" %>
  <%= stylesheet_link_tag "mime2" %>
  
  <div class="form-group"> 
  <%= form.label :Title %>
  <%= form.text_field :title, class: 'form-control' %></div>
  <% if t == 1 %>
    <div style="color:red"> This field is required </div>
    <br>
  <% end %>
  
  <div class="form-group">
    <%= form.label :Description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <% if d == 1 %>
    <div style="color:red"> This field is required </div>
    <br>
  <% end %>

  <table style="width:50%">
    <tr>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <td><%= form.label :Assignee, style: "font-size:17px;" %></td>
        <td><%= form.select(:name, User.all.collect { |v| [ v.username, v.username ] },
                 {}, { "data-placeholder": "Select assignee" }) %></td>
    </tr>
    <tr>
        <td><%= form.label :"Status", style: "font-size:17px;" %></td>
        <td><% if @issue.status.blank? %>
                    <%= form.select :status, ["NEW","DUPLICATE", "RESOLVED", "INVALID", "ON HOLD"], :selected => "NEW", :class => 'genForm_dropBox'  %>
                <% else %>
                    <%= form.select :status, ["NEW","DUPLICATE", "RESOLVED", "INVALID", "ON HOLD"], :selected => @issue.status, :class => 'genForm_dropBox' %>
                <% end %></td>
    </tr>
    <tr>
        <td><%= form.label :type, style: "font-size:17px;" %></td>
        <td><% if @issue.tipus.blank? %>
                    <%= form.select :tipus,["BUG", "ENHANCEMENT", "PROPOSAL", "TASK"], :selected => "BUG", :class => 'genForm_dropBox' %>
                <% else %>
                    <%= form.select :tipus, ["BUG", "ENHANCEMENT", "PROPOSAL", "TASK"], :selected => @issue.tipus, :class => 'genForm_dropBox' %>
                <% end %></td>
    </tr>
    <tr>
        <td><%= form.label :priority, style: "font-size:17px;" %></td>
        <td><% if @issue.priority.blank? %>
                    <%= form.select :priority, ["MAJOR", "TRIVIAL", "MINOR", "CRITICAL", "BLOCKER"], :selected => "MAJOR", :class => 'genForm_dropBox' %>
                <% else %>
                    <%= form.select :priority, ["MAJOR", "TRIVIAL", "MINOR", "CRITICAL", "BLOCKER"], :selected => @issue.priority, :class => 'genForm_dropBox' %>
            <% end %></td>
    </tr>
  </table>

  <br>
  <div class="row" style="margin-top:10px; margin-left:180px; margin-right:200px">
        <div class="col-md-6" style="">
            <%= form.submit :Confirm , data: { disable_with: false }, class: "btn btn-primary" %>
        </div>
        <div class="col-md-2 offset-md-4" style="">
            <%= link_to 'Back', issues_path, class: "btn btn-primary", style: "color:white;border-color:black;background-color:black" %>
        </div>
  </div>

<% end %>

app/views/issues/_form_comment.html.erb
  <%= form_for :comment, url: {action: "comment", params: {id: @issue.id}}  do |form| %>

  <% if @comment.present? %>
  <% t = 0
     if @comment.errors.any? 
        if @comment.errors.include? 'text'
            t = 1
        end
     @comment.errors.clear
     end%>
  <% end %>

  <%= stylesheet_link_tag "mime1" %>
  <%= stylesheet_link_tag "mime2" %>

  <div class="form-group" style="margin-top:40px">
    <% if t == 1 %>
    <div style="color:red"> This field is required </div>
    <br>
  <% end %>
  <img src='<%= current_user.avatar_url %>' style="display: inline;height:36px; border-radius:18px; margin-right:20px;margin-bottom:20px"/>
  <%= form.text_area :text, placeholder: "What do you want to say?", style:"width: 75%;",  class: 'form-control' %>
<%= form.submit :Create , data: { disable_with: false }, style: "color:black;border-color:black;background-color:white;display:inline;position: absolute;right: 15px;", class: "btn btn-primary" %>
  <div>
      <%= form.label :Attachment %>
      <label class="custom-file-upload" style="margin-left:10px">
            Upload new attachment
            <span style="display:none;">
                <%= form.file_field :attachment_identifier %>
            </span>
        </label>
    </div>
  </div>

<% end %>

app/views/issues/_form_comment_2.html.erb
  <%= form_for :comment, :url => "/issues/"+@issue.id.to_s+"/comments/"+@comment.id.to_s, :method => "patch"  do |form| %>
  <% if @comment.present? %>
  <% t = 0
     if @comment.errors.any? 
        if @comment.errors.include? 'text'
            t = 1
        end
     @comment.errors.clear
     end%>
  <% end %>

  <%= stylesheet_link_tag "mime1" %>
  <%= stylesheet_link_tag "mime2" %>

  <div class="form-group" style="margin-top:40px">
    <% if t == 1 %>
    <div style="color:red"> This field is required </div>
    <br>
  <% end %>
  <img src='<%= current_user.avatar_url %>' style="display: inline;height:50px; border-radius:18px; margin-right:10px;margin-bottom:30px"/>
  <%= form.text_area :text, placeholder: "What do you want to say?", style:"width: 85%;",  class: 'form-control' %>
  </div>
    <% com=Comment.find_by_id(params[:comment_id])%>
    <% if !com.post.blank? %>
      <div>
        <%= form.label :"Change Attachment" %>
        <label class="custom-file-upload" style="margin-left:10px">
            Upload new attachment
            <span style="display:none;">
                <%= form.file_field :attachment_identifier %>
            </span>
        </label>
      </div>
      <div>
      <br>
        Remove attachments: <%= form.check_box :kill, {}, "true", "false" %>
      </div>
    <% else %>
      <div>
        <%= form.label :"Add attachment" %>
        <label class="custom-file-upload" style="margin-left:10px">
            Upload new attachment
            <span style="display:none;">
                <%= form.file_field :attachment_identifier %>
            </span>
        </label>
      </div>
    <% end %>
    <br>
    <div class="row" style="margin-top:10px; margin-left:180px; margin-right:200px">
        <div class="col-md-6" style="">
            <%= form.submit :Confirm , data: { disable_with: false }, style: "color:white;border-color:black;background-color:black", class: "btn btn-primary" %>
        </div>
        <div class="col-md-2 offset-md-4" style="">
            <%= link_to 'Back', issue_path(@issue), class: "btn btn-primary", style: "color:white;border-color:black;background-color:black" %>
        </div>
  </div>

<% end %>

app/views/issues/_form_post.html.erb
  <%= form_for :post, url: {action: "create"} do |form| %>

  <%= stylesheet_link_tag "mime1" %>
  <%= stylesheet_link_tag "mime2" %>
  
  <div class="form-group" style="margin-top:40px"> 
    <div>
      <%= form.label :file %>
      <%= form.file_field :image %>

  </div>
  <%= form.submit :Create , data: { disable_with: false }, style: "color:black;border-color:black;background-color:white;display:inline;position: absolute;right: 15px;", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/issues/index.html.erb
<%= stylesheet_link_tag "mime1" %>
<%= stylesheet_link_tag "mime2" %>
<!DOCTYPE html>
<html>
<%
  if current_user.blank?

  else
    username = current_user.username;
    avatar_url = current_user.avatar_url;
  end
%>
<head>
<meta charset="utf-8">
<title>Issues</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark navbar-dark" >
<div class="container" > <button class="navbar-toggler navbar-toggler-right border-0 p-0" type="button" data-toggle="collapse" data-target="#navbar14">
<p align="center" class="navbar-brand mb-0 text-white">
<i class="fa d-inline fa-lg fa-stop-circle"></i> ISSUE TRACKER </p>
</button>
<div class="collapse navbar-collapse" id="navbar14">
<ul class="navbar-nav mr-auto">
<li class="nav-item"> <a class="nav-link" href="<%= getHostFromIssues %>">Issues</a> </li>
</ul>
<p class="d-none d-md-block lead mb-0  text-white"> <i class="fa d-inline fa-lg fa-stop-circle"></i> <b> ISSUE TRACKER</b> </p>
<ul class="navbar-nav ml-auto">

<% if current_user.blank? %>
<li class="nav-item"> <a class="nav-link" href='<%= getHostFromIssues + 'sessions/new' %>'>Sign in</a> </li>
<% else %>
<li class="nav-item"> <a class="nav-link"><%= username %></a> </li>
<li class="nav-item"> <img src='<%= avatar_url%>' style="height:36px; border-radius:18px; margin-right:20px;"/> </li>
<li class="nav-item"> <a class="nav-link" href='<%= getHostFromIssues + 'sessions/new' %>'>Log Out</a> </li>
<% end %>
</ul>
</div>
</div>
</nav>
<div style="margin: auto; margin-top: 60px; width: 1200px; max-width: 90%; margin-bottom:40px">
<p id="notice"><%= notice %></p>

<h1 style="margin-bottom: 30px;">Issues</h1>

<% if !current_user.blank? %>
<button onclick="myFunction()" class="btn btn-primary" style="color:black;border-color:#D3D3D3;background-color:#D3D3D3;margin-bottom:10px">Generate API Token</button>
<div id="divToken" class="card bg-light mb-3" style ="display: none">
    <div class="card-header" style="display:flex; flex-direction:row; justify-content:space-between;font-size:17px;font-weight:bold;">
        <h>API access</h>
    </div>
    <div class="card-body">
        <h>You can check the operations clicking in this <a href="https://blooming-forest-68248.herokuapp.com/api-docs/index.html">link</a>. Use this generated key to acces the different methods:
            <%= if !current_user.blank? && !current_user.api_token.blank? 
                    current_user.api_token.token 
            end%>
        </h>
    </div>
</div>

<script>
function myFunction() {
  var x = document.getElementById("divToken");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

<%end%>

<table class="table table-hover">
<thead>
<tr>
<th><%= link_to "Title", manage_order('title'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_title" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %></th>
<th style="width: 60px;">
  <%= link_to "T", manage_order('tipus'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_tipus" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>  
<th style="width: 60px;">
  <%= link_to "P", manage_order('priority'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_priority" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 60px;">
  <%= link_to "Status", manage_order('status'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_status" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 85px;">
  <%= link_to "Votes", manage_order('votes'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_votes" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 160px;">
  <%= link_to "Assignee", manage_order('assignee'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_user" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 120px;">
  <%= link_to "Created", manage_order('created'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_created" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 120px;">
  <%= link_to "Updated", manage_order('updated'), style:"color:#666;" %>
  <% if request.original_url.include? "ordered_by_updated" %>
    <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
  <% end %>
</th>
<th style="width: 120px;">
  <% if current_user.blank? %>
  <img src="https://image.flaticon.com/icons/svg/159/159604.svg" style="color:#666; height:26px;">
  <% else %>
    <%= link_to image_tag("https://image.flaticon.com/icons/svg/159/159604.svg", height: 26), manage_order('follow'), style:"color:#666;" %>
    <% if request.original_url.include? "ordered_by_follow" %>
      <img src="https://image.flaticon.com/icons/svg/32/32195.svg" style="height: 15px;">
    <% end %>
  <% end %>
</th>
</tr>
</thead>
<tbody>
<% @issues.each do |issue| %>
  <tr onclick="window.location.href = '<%= getHostFromIssues + 'issues/' + issue.id.to_s %>';">
  <th scope="row"><%= issue.title %></th>
  <td>
  <div class="has-link">
  <%= link_to issue.tipus, manage_filters('tipus', issue.tipus), style:"color:#666;" %>
  </div>
  </td>
  <td>
  <div class="has-link">
  <%= link_to issue.priority, manage_filters('priority', issue.priority), style:"color:#666;" %>
  </div>
  </td>
  <td>
  <div class="has-link">
  <%= link_to issue.status, manage_filters('status', issue.status), style:"color:#666;" %>
  </div>
  </td>
  <td><%= issue.votes %></td>
  <td>
  <div class="has-link">
  <img src="<%= User.find_by_username(issue.stringassign).avatar_url %>" style="height:26px; border-radius:13px;" />

  <%= link_to issue.stringassign, manage_filters('assign', issue.stringassign), style:"color:#666;" %>
  </div>
  </td>
  <td><%= issue.created %></td>
  <td><%= issue.updated %></td>
  <td>
    <% if isFollowing(issue) %>
      Following
    <% else %>
      Not following
    <% end %>
  </td>
  </tr>
  <% end %>
  </tbody>
  </table>
  
  <br>
  
  <div style="display:flex; flex-direction:row;padding-bottom:100px">
  <% if request.original_url.include? '?' %>
  <%= link_to 'Delete filters', issues_path, class: "btn btn-primary", style: "color:white;border-color:black;background-color:black" %>
  <% end %>
  <div style="margin-left:10px;">
  <% if current_user.blank? %>
  <p style="color:darkred;">You need to be logged in to create a new issue</p>
  <% else %>
  <%= link_to 'New Issue', new_issue_path, class: "btn btn-primary", style: "position:absolute;margin-bottom:100px;color:white;border-color:black;background-color:black" %>
  <% end %>
  </div>
  </div>

  </div>
  <div class="footer" style="color:white;padding-top:25px;padding-bottom:20px">
  <p style="text-align:center;">©2019 Issue Tracker For Student Purposes</p>
  </div>

  <script>
  Array.prototype.slice.call(document.getElementsByClassName("has-link")).forEach((e) => e.addEventListener('click', (event) => event.stopPropagation()));
  </script>

  </body>